version: '3.8'

services:
  postgres:
    container_name: postgres_container_memo
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password-root
      POSTGRES_DB: memo_backend
    ports:
      - "6432:5432"
    networks:
      - memo-backend
    restart: unless-stopped
    volumes:
      - pgsql-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  pgsql-data:
    driver: local

networks:
  memo-backend:
    driver: bridge