@startuml

class Tip {
    # String command
    # String description
    # Integer createdAt
    # Integer updatedAt
}

class Environment {
    # String name
    # String details
    # Integer createdAt
    # Integer updatedAt
}

Tip "0..*" - "1..1" Environment

@enduml