@startuml

class Tips {
    # String tips
    # String description
    # Integer createdAt
    # Integer updatedAt
}

class Environment {
    # String name
    # String details
    # Integer createdAt
    # Integer updatedAt
}

Tips "0..*" - "1..1" Environment

@enduml